LOAD DATA LOCAL INFILE 'CSV/publications_authors_rem.csv'
INTO TABLE authors_have_publications
CHARACTER SET UTF8
FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY '\\'
LINES TERMINATED BY '\n' STARTING BY '' 
;
LOAD DATA LOCAL INFILE 'CSV/publications_content_rem.csv'
INTO TABLE Titles_published_as_Publications
CHARACTER SET UTF8
FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY '\\'
LINES TERMINATED BY '\n' STARTING BY '' 
;
LOAD DATA LOCAL INFILE 'CSV/webpages_rem.csv'
INTO TABLE Webpages_temp
CHARACTER SET UTF8
FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY '\\'
LINES TERMINATED BY '\n' STARTING BY '' 
;
